version: '3.8'
services:
  testing-agent:
    build: .
    ports:
      - "3000:3000"
      - "3005:3005" 
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run dev
